#!/bin/bash

set -e

echo '+cargo clippy --all-features --all-targets -- -D warnings -W clippy::dbg_macro'
cargo clippy --all-features --all-targets -- -D warnings -W clippy::dbg_macro
echo '+cargo fmt -- --check'
cargo fmt -- --check