name: Release

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    permissions:
      contents: "write"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.60.0
          override: true

      - name: Install Cargo Edit
        run: cargo install cargo-edit

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Assign Release Version from Tag
        run: |
          cargo set-version $RELEASE_VERSION
          cargo update --package benchie --precise $RELEASE_VERSION

      - name: Commit Version Update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Cargo.toml
          git add Cargo.lock
          git commit --no-verify -m "set release version on CI build [ci skip]"
          git push

      - name: Publish on crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}